apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: bestbuy
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: hebenben/product-service-bestbuy:v1
          ports:
            - name: http
              containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: bestbuy
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - name: http
      port: 3002
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: bestbuy
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: hebenben/order-service-bestbuy:v2
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_DB
            - name: ORDER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_DB
            - name: ORDER_DB_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_DB_COLLECTION_NAME
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: MONGO_PASSWORD
            - name: ORDER_DB_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(ORDER_DB_NAME)?authSource=admin"
            - name: ORDER_QUEUE_URI
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_URI
            - name: ORDER_QUEUE_HOSTNAME
              value: "rabbitmq"
            - name: ORDER_QUEUE_PORT
              value: "5672"
            - name: ORDER_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_NAME
            - name: ORDER_QUEUE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: ORDER_QUEUE_USERNAME
            - name: ORDER_QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: ORDER_QUEUE_PASSWORD
            - name: ORDER_QUEUE_RECONNECT_LIMIT
              value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: bestbuy
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
  namespace: bestbuy
  labels:
    app: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
        - name: makeline-service
          image: hebenben/makeline-service-bestbuy:v1
          ports:
            - name: http
              containerPort: 3001
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_DB
            - name: ORDER_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_DB
            - name: ORDER_DB_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_DB_COLLECTION_NAME
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: MONGO_PASSWORD
            - name: ORDER_DB_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(ORDER_DB_NAME)?authSource=admin"
            - name: ORDER_QUEUE_URI
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_URI
            - name: ORDER_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_NAME
            - name: ORDER_QUEUE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: ORDER_QUEUE_USERNAME
            - name: ORDER_QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secret
                  key: ORDER_QUEUE_PASSWORD
            - name: ORDER_QUEUE_POLL_INTERVAL_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_QUEUE_POLL_INTERVAL_SECONDS
            - name: ORDER_WORKER_INTERVAL_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_WORKER_INTERVAL_SECONDS
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
  namespace: bestbuy
  labels:
    app: makeline-service
spec:
  type: ClusterIP
  selector:
    app: makeline-service
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
  namespace: bestbuy
  labels:
    app: store-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - name: store-front
          image: hebenben/store-front-bestbuy:v1
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-front
  namespace: bestbuy
  labels:
    app: store-front
spec:
  type: LoadBalancer
  selector:
    app: store-front
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
  namespace: bestbuy
  labels:
    app: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: hebenben/store-admin-bestbuy:v1
          ports:
            - name: http
              containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
  namespace: bestbuy
  labels:
    app: store-admin
spec:
  type: LoadBalancer
  selector:
    app: store-admin
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
