apiVersion: v1
kind: ConfigMap
metadata:
  name: bestbuy-config
  namespace: bestbuy
data:
  MONGO_HOST: mongodb
  MONGO_PORT: "27017"
  MONGO_DB: orderdb
  ORDER_DB_COLLECTION_NAME: orders
  ORDER_QUEUE_NAME: orders
  ORDER_QUEUE_URI: amqp://rabbitmq
  ORDER_QUEUE_POLL_INTERVAL_SECONDS: "5"
  ORDER_WORKER_INTERVAL_SECONDS: "10"
  ORDER_SERVICE_URL: http://order-service:3000
  VUE_APP_PRODUCT_SERVICE_URL: http://product-service:3002
  VUE_APP_ORDER_SERVICE_URL: http://order-service:3000
  VUE_APP_MAKELINE_SERVICE_URL: http://makeline-service:3001
